---
title: "Senior Project"
author: "Jonathan"
date: "2023-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Read in the CSV of the data
```


```{r}
#CSV created in Python

df_analysis <- read.csv('analysis.csv')
df_analysis 
```

```{r}
# Keep only countries with HDI data

df_analysis = subset(df_analysis, !is.na(HDI))
```


```{r}
# Create new category variable for developed and developing countries, based on HDI

df_developed = subset(df_analysis, Category == 'Developed')
df_developing = subset(df_analysis, Category == 'Developing')
```

```{r}
# Developed countries correlation between Log GDPPC and CO2 Emissions
cor(df_developed$Log_GDPPC, df_developed$CO2_Emissions, method = 'pearson')
cor.test(df_developed$Log_GDPPC, df_developed$CO2_Emissions, method = 'pearson')
```

```{r}
# Developing countries correlation between Log GDPPC and CO2 Emissions
cor(df_developing$Log_GDPPC, df_developing$CO2_Emissions, method = 'pearson')
cor.test(df_developing$Log_GDPPC, df_developing$CO2_Emissions, method = 'pearson')
```

```{r}
# SLR

mod_all = lm(CO2_Emissions ~ Log_GDPPC, data = df_analysis)
summary(mod_all)
```


```{r}
# Developed countries linear model
mod_developed = lm(CO2_Emissions ~ Log_GDPPC, data = df_developed)
summary(mod_developed)
```

```{r}
# Developing countries linear model

mod_developing = lm(CO2_Emissions ~ Log_GDPPC, data = df_developing)
summary(mod_developing)
```

```{r}
# Multi Regression of Developed

mod_multi_developed = lm(CO2_Emissions ~ Log_GDPPC + Renewable + Electricity, data = df_developed)
summary(mod_multi_developed)
```

```{r}
# Multi Regression of developing

mod_multi_developing = lm(CO2_Emissions ~ Log_GDPPC + Renewable + Electricity, data = df_developing)
summary(mod_multi_developing)
```





